import { Roboto } from "next/font/google";
import "./globals.css"; // لتحميل ملفات CSS العامة
import "bootstrap/dist/css/bootstrap.min.css";
import App from "./_components/App";
import Head from "next/head";

const inter = Roboto({ subsets: ["latin"], weight: "700" });

export const metadata = {
  title: "auth Product",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={`${inter.className}`}>
        <App childrenData={children} />
      </body>
    </html>
  );
}
