export const ROLES = {
  ADMIN: "admin",
  EDITOR: "editor",
  USER: "user",
};

export const PERMISSIONS = {
  VIEW_DASHBOARD: "VIEW_DASHBOARD",
  EDIT_PRODUCTS: "EDIT_PRODUCTS",
  VIEW_PRODUCTS: "VIEW_PRODUCTS",
  VIEW_CATEGORIES: "VIEW_CATEGORIES",
  EDIT_CATEGORIES: "EDIT_CATEGORIES",
};
export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.EDIT_PRODUCTS,
    PERMISSIONS.VIEW_PRODUCTS,
    PERMISSIONS.VIEW_CATEGORIES,
    PERMISSIONS.EDIT_CATEGORIES,
  ],
  [ROLES.EDITOR]: [
    PERMISSIONS.VIEW_PRODUCTS,
    PERMISSIONS.EDIT_PRODUCTS,
    PERMISSIONS.VIEW_CATEGORIES,
  ],
  [ROLES.USER]: [PERMISSIONS.VIEW_PRODUCTS, PERMISSIONS.VIEW_CATEGORIES],
};
